---
abstract: unknown
author:
  - unknown
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Fast
no_index:
  directory:
    - t
    - inc
    - t
requires:
  CGI: 3.6502
  FCGI: 0.67
  File::Spec: 0.82
  Test::More: 0.98
  if: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/leejo/cgi-fast/issues
  homepage: https://metacpan.org/module/CGI::Fast
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/cgi-fast
version: 1.10_01
